name: safewalk_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mapbox_maps_flutter: ^2.18.0
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  provider: ^6.0.5
  http: ^1.6.0
  permission_handler: ^11.2.0
  google_places_api_flutter: ^2.0.0
  flutter_polyline_points: ^3.1.0
  flutter_dotenv: ^6.0.0
  flutter_compass: ^0.8.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.0
  flutter_contacts: ^1.1.9+1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#0D1B2A"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/london_collisions.json
    - assets/icon/app_icon.png